# Generated by Django 3.0.3 on 2020-02-27 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dtime_news_core.permissions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=30)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='English Content')),
                ('expert_text', models.TextField(blank=True, null=True, verbose_name='Expert Text')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('published', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='published')),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('publish', 'Published'), ('un-publish', 'Un-Publish')], default='un-publish', max_length=30)),
                ('show_in_slide', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('drafting', 'Drafting'), ('waiting', 'Waiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='drafting', max_length=30)),
                ('visited_count', models.PositiveIntegerField(default=0, verbose_name='visited_count')),
                ('categories', models.ManyToManyField(related_name='news', to='news.Category', verbose_name='categories')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_news', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            bases=(models.Model, dtime_news_core.permissions.BaseGlobalMixin, dtime_news_core.permissions.BaseObjectMixin),
        ),
        migrations.CreateModel(
            name='NewsAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submited', 'Submit'), ('approved', 'Approve'), ('rejected', 'Reject')], default='submited', max_length=30)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_actions', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_actions', to='news.News', verbose_name='news')),
            ],
        ),
    ]
