# Generated by Django 3.0.3 on 2020-02-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='link url'),
        ),
    ]
