# Generated by Django 3.0.3 on 2020-03-05 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200228_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sub_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_menus', to='news.Menu', verbose_name='sub menu'),
        ),
    ]
