# Generated by Django 3.0.3 on 2020-03-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200305_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_parent',
        ),
        migrations.AlterField(
            model_name='menu',
            name='sub_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_menus', to='news.Menu', verbose_name='main menu'),
        ),
    ]
