# Generated by Django 3.0.3 on 2020-03-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200305_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='sub_menu',
            new_name='main_menu',
        ),
    ]
