# Generated by Django 3.0.3 on 2020-03-09 11:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0011_auto_20200305_0734'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True, verbose_name='gender')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='phone number')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date of birth')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('role', models.CharField(choices=[('viewer', 'viewer'), ('editor', 'editor'), ('categorized_content_approver', 'categorized content approver'), ('admin_content_approver', 'admin content approver'), ('system_admin', 'system admin'), ('super_admin', 'super adminn')], default='viewer', max_length=50, verbose_name='role')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='user_profile/')),
                ('news_categories', models.ManyToManyField(blank=True, null=True, related_name='user_profile', to='news.Category', verbose_name='news categories')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
